name: Setup ZeroTier on RDP

on:
  workflow_dispatch:

jobs:
  zerotier-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Update System
        run: |
          sudo apt update
          sudo apt upgrade -y

      - name: Install ZeroTier
        run: |
          curl -s https://install.zerotier.com | sudo bash
          sudo systemctl enable zerotier-one
          sudo systemctl start zerotier-one

      - name: Join ZeroTier Network
        run: |
          NETWORK_ID="gzDZdpaTV4EJ6hNagOfQ2IddcaR3VGsh"
          sudo zerotier-cli join $NETWORK_ID
          sleep 5
          STATUS=$(sudo zerotier-cli info)
          echo "ZeroTier Status: $STATUS"

      - name: Get ZeroTier IP
        run: |
          ZT_IP=$(ip addr show zt0 | grep 'inet ' | awk '{print $2}' | cut -d/ -f1)
          echo "Your RDP ZeroTier IP is: $ZT_IP"
