name: Windows RDP with Proxy

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin "MySecurePass123"  # password for RDP
      - name: Print RDP Info
        run: |
          echo "RDP IP: $env:COMPUTERNAME"
          echo "Username: runneradmin"
          echo "Password: MySecurePass123"

  proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y tinyproxy unzip wget

      - name: Configure tinyproxy
        run: |
          sudo sed -i 's/Allow 127.0.0.1/Allow 0.0.0.0/g' /etc/tinyproxy/tinyproxy.conf
          sudo sed -i 's/^#Port 8888/Port 8888/' /etc/tinyproxy/tinyproxy.conf
          sudo systemctl restart tinyproxy

      - name: Download ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          ./ngrok authtoken 33HpBIgSbFICtuzGqCKopz11ZDb_eGr4t95nKnkkjujyHD2P

      - name: Start ngrok TCP tunnel
        run: |
          nohup ./ngrok tcp 8888 &
          sleep 10
          curl -s localhost:4040/api/tunnels
