name: RDP + Exit Node

on:
  workflow_dispatch:

jobs:
  windows-rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Configure RDP
        run: |
          # Enable RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force

          # Firewall rule for RDP
          netsh advfirewall firewall delete rule name="RDP-Allow"
          netsh advfirewall firewall add rule name="RDP-Allow" dir=in action=allow protocol=TCP localport=3389

          Restart-Service -Name TermService -Force

      - name: Create Fixed RDP User
        run: |
          $password = ConvertTo-SecureString "Abhash@#&12+-" -AsPlainText -Force
          if (-not (Get-LocalUser -Name "AbhashPatel" -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name "AbhashPatel" -Password $password -AccountNeverExpires
            Add-LocalGroupMember -Group "Administrators" -Member "AbhashPatel"
            Add-LocalGroupMember -Group "Remote Desktop Users" -Member "AbhashPatel"
          }

      - name: Install Tailscale
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force

      - name: Connect Tailscale + Exit Node
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up `
            --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} `
            --hostname=abhash-rdp `
            --advertise-exit-node

          # Print the assigned IP/domain
          $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
          Write-Host "Tailscale IP: $tsIP"

      - name: Keep Alive
        run: |
          Write-Host "`n=== RDP & Exit Node READY ==="
          Write-Host "Username: AbhashPatel"
          Write-Host "Password: Abhash@#&12+-"
          Write-Host "================================"
          while ($true) {
            Write-Host "[$(Get-Date)] Running..."
            Start-Sleep -Seconds 300
          }
