name: RDP-WireGuard-VPN-Setup

on:
  workflow_dispatch:

jobs:
  setup-vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Update System
        run: |
          sudo apt update
          sudo apt upgrade -y

      - name: Install WireGuard
        run: |
          sudo apt install -y wireguard

      - name: Generate Server Keys
        run: |
          mkdir -p ~/wireguard-keys
          wg genkey | tee ~/wireguard-keys/server_private.key | wg pubkey > ~/wireguard-keys/server_public.key

      - name: Generate Client Keys
        run: |
          wg genkey | tee ~/wireguard-keys/client_private.key | wg pubkey > ~/wireguard-keys/client_public.key

      - name: Configure WireGuard Server
        run: |
          SERVER_PRIVATE_KEY=$(cat ~/wireguard-keys/server_private.key)
          CLIENT_PUBLIC_KEY=$(cat ~/wireguard-keys/client_public.key)
          sudo bash -c 'cat > /etc/wireguard/wg0.conf <<EOF
[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = '$SERVER_PRIVATE_KEY'

[Peer]
PublicKey = '$CLIENT_PUBLIC_KEY'
AllowedIPs = 10.0.0.2/32
EOF'

      - name: Enable and Start WireGuard
        run: |
          sudo systemctl enable wg-quick@wg0
          sudo wg-quick up wg0

      - name: Output Client Config for Phone
        run: |
          CLIENT_PRIVATE_KEY=$(cat ~/wireguard-keys/client_private.key)
          SERVER_PUBLIC_KEY=$(cat ~/wireguard-keys/server_public.key)
          SERVER_IP=$(curl -s ifconfig.me)
          echo "[Interface]
PrivateKey = $CLIENT_PRIVATE_KEY
Address = 10.0.0.2/24

[Peer]
PublicKey = $SERVER_PUBLIC_KEY
Endpoint = $SERVER_IP:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25" > ~/wireguard-keys/client-phone.conf
          cat ~/wireguard-keys/client-phone.conf
